Stretched instr_valid_irq_flush_q pulse so that it is not missed if t…
openhwgroup/cv32e40p pull request #451
Opened 2020-08-19 07:35 UTC by Silabs-ArjanB

Stretched instr_valid_irq_flush_q pulse so that it is not missed if the instruction after a IRQ_FLUSH to DECODE transition experiences stalls (fix for #449 and partial fix for #439 #440 #441 #442) 

- [ ] Please review the stretch condition 'if (id_valid_i)'. The reason I picked that signal is because the 'tracer' judges the end of decoding by 'if ( id_valid && is_decoding )'

Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

2020-08-19 08:27 UTC, Silabs-ArjanB commented
Commit 92b2300 takes care of setting illegal_insn_n back to 0 when a new instruction is in the DECODE state. Without this an instruction following an illegal instruction could get classified as an illegal instruction itself. See below waveform for an example. In this example 0x00045413 is an illegal instruction. However instruction 0x0000000f gets classified as illegal as well even though illegal_insn_i = 0 (because illegal_insn_n is simply a default copy of illegal_insn_q).

Together with the previous commit this should now fix #439 #440 #441 #442 

![image](https://user-images.githubusercontent.com/40633348/90610577-e8670180-e205-11ea-8ed8-f0d57a8ee52c.png)

2020-08-19 09:55 UTC, Silabs-ArjanB commented
I want to do one more change in cv32e40p_decoder by replacing the following code:

              12'h302:  // mret
              begin
                illegal_insn_o = (PULP_SECURE) ? current_priv_lvl_i != PRIV_LVL_M : 1'b0;
                mret_insn_o    = ~illegal_insn_o;
                mret_dec_o     = 1'b1;
              end

              12'h002:  // uret
              begin
                illegal_insn_o = (PULP_SECURE) ? 1'b0 : 1'b1;
                uret_insn_o    = ~illegal_insn_o;
                uret_dec_o     = 1'b1;
              end

              12'h7b2:  // dret
              begin
                illegal_insn_o = !debug_mode_i;
                dret_insn_o    =  debug_mode_i;
                dret_dec_o     =  1'b1;
              end

by:

              12'h302:  // mret
              begin
                illegal_insn_o = (PULP_SECURE) ? current_priv_lvl_i != PRIV_LVL_M : 1'b0;
                mret_insn_o    = ~illegal_insn_o;
              end

              12'h002:  // uret
              begin
                illegal_insn_o = (PULP_SECURE) ? 1'b0 : 1'b1;
                uret_insn_o    = ~illegal_insn_o;
              end

              12'h7b2:  // dret
              begin
                illegal_insn_o = !debug_mode_i;
                dret_insn_o    =  debug_mode_i;
              end

and replacing all uses of mret_dec_o by mret_insn_o, uret_dec_o by uret_insn_o, and dret_dec_o by dret_insn_o.

To me it seems weird that these *_dec_o signals are 1 when their corresponding *_insn_o signal is 0.

Okay with above change 

- [ ] (then I will make a commit for that)?

2020-08-19 10:00 UTC, Silabs-ArjanB commented
- [ ] Hi @shetalani , could you please run OneSpin's formal checks on the proposed Silabs-ArjanB:ArjanB_illegal_instr_exc commit and check whether #438, #439, #440, #441, #442 have been solved or not (and if no new issues arose)? (Please mark the check box if okay and otherwise leave a comment on what is wrong)

2020-09-01 15:48 UTC, shetalani commented
> * [x]  Hi @shetalani , could you please run OneSpin's formal checks on the proposed Silabs-ArjanB:ArjanB_illegal_instr_exc commit and check whether #438, #439, #440, #441, #442 have been solved or not (and if no new issues arose)? (Please mark the check box if okay and otherwise leave a comment on what is wrong)

All the 5 issues are fixed. Cheers!

2020-09-01 17:17 UTC, davideschiavone commented
> 
> 
> Commit [92b2300](https://github.com/openhwgroup/cv32e40p/commit/92b2300524a3ff0d206dd3e8623d533115e602bb) takes care of setting illegal_insn_n back to 0 when a new instruction is in the DECODE state. Without this an instruction following an illegal instruction could get classified as an illegal instruction itself. See below waveform for an example. In this example 0x00045413 is an illegal instruction. However instruction 0x0000000f gets classified as illegal as well even though illegal_insn_i = 0 (because illegal_insn_n is simply a default copy of illegal_insn_q).
> 
> Together with the previous commit this should now fix #439 #440 #441 #442
> 
> Also added an assertion to check that mepc and illegal instruction encounter are consistent.
> 
> ![image](https://user-images.githubusercontent.com/40633348/90610577-e8670180-e205-11ea-8ed8-f0d57a8ee52c.png)

Hello @Silabs-ArjanB ,

in this example (just for my understanding) the following happens:

We have an illegal instruction
The core would like to go to FLUSH_EX but it is blocked by id_ready (maybe a stall in a previous ld/st instruction)
Then we receive an interrupt, I see the core going to IRQ_FLUSH
Then we go to TAKEN_ID
As now the illegal_insn_q is 1, the core thinks that the first instruction of the ISR is illegal.

Is that correct?

2020-09-01 17:39 UTC, davideschiavone commented
> illegal_insn_o



> mret_insn_o

I honestly don't know why we have mret_dec and not insn. It may be from old controlling logic but first impression looks ok. Can it happens that we have mret_insn_o switching from 1 to 0 or viceversa ?
I am almost sure it comes from PULP_SECURE race conditions.

2020-09-01 17:41 UTC, davideschiavone requested changes

2020-09-01 17:41 UTC, davideschiavone commented on rtl/cv32e40p_core.sv
> +  always_ff @(posedge clk , negedge rst_ni)
Can we have this part somehow explicitly saying that is not for synthesis but rather check? maybe we can move it to the BHV folder

2020-09-01 18:50 UTC, Silabs-ArjanB commented on rtl/cv32e40p_core.sv
> +  always_ff @(posedge clk , negedge rst_ni)
All asssertions and related logic (like the one you commented on) inside `ifdef CV32E40P_ASSERT_ON `endif constructs will be moved out of the RTL files into the new sva (System Verilog Assertions' directory as proposed by Mike here: https://github.com/openhwgroup/cv32e40p/pull/421/files

2020-09-02 07:26 UTC, Silabs-ArjanB commented
> 
> 
> > Commit [92b2300](https://github.com/openhwgroup/cv32e40p/commit/92b2300524a3ff0d206dd3e8623d533115e602bb) takes care of setting illegal_insn_n back to 0 when a new instruction is in the DECODE state. Without this an instruction following an illegal instruction could get classified as an illegal instruction itself. See below waveform for an example. In this example 0x00045413 is an illegal instruction. However instruction 0x0000000f gets classified as illegal as well even though illegal_insn_i = 0 (because illegal_insn_n is simply a default copy of illegal_insn_q).
> > Together with the previous commit this should now fix #439 #440 #441 #442
> > Also added an assertion to check that mepc and illegal instruction encounter are consistent.
> > ![image](https://user-images.githubusercontent.com/40633348/90610577-e8670180-e205-11ea-8ed8-f0d57a8ee52c.png)
> 
> Hello @Silabs-ArjanB ,
> 
> in this example (just for my understanding) the following happens:
> 
> We have an illegal instruction
> The core would like to go to FLUSH_EX but it is blocked by id_ready (maybe a stall in a previous ld/st instruction)
> Then we receive an interrupt, I see the core going to IRQ_FLUSH
> Then we go to TAKEN_ID
> Then first instruction of the ISR is an instruction that needs FLUSH (fence in this example)
> As the illegal_insn_q is 1, the core thinks that the first instruction of the ISR is illegal.
> 
> Is that correct?

Hi @davideschiavone Yes, your understanding is correct. The fact that the first instruction in the ISR needs a flush is not really relevant for this example though. Any first instruction of the ISR would have been marked as illegal. As you can see in my fix I only forced illegal_insn_n back to 0 when we get back in the DECODE state (I did not try to alter the assignment to illegal_insn_q, as I do not fully oversee the use of that signal).

2020-09-02 08:30 UTC, merged

2020-09-02 09:12 UTC, Silabs-ArjanB commented
> 
> 
> > illegal_insn_o
> 
> > mret_insn_o
> 
> I honestly don't know why we have mret_dec and not insn. It may be from old controlling logic but first impression looks ok. Can it happens that we have mret_insn_o switching from 1 to 0 or viceversa ?
> I am almost sure it comes from PULP_SECURE race conditions.

I truly do not see the reason behind the current definition of the mret_dec_o, uret_dec_o, dret_dec_o signals. If I make them identical to mret_insn_o, uret_insn_o, dret_insn_o respectively, the CV32E40P is still logically equivalent. Anyway, I left that code as is (as it doesn't cause any issues either).