:recycle: clean up apu interface
openhwgroup/cv32e40p pull request #558
Opened 2020-10-26 21:11 UTC by davideschiavone

2020-10-27 07:11 UTC, Silabs-ArjanB requested changes
Hi Davide, the changes look good. Can you go a bit further though and also clean up include/cv32e40p_apu_core_pkg.sv. As ar as I can see at least all APU_FLAGS* and WAPUTYPE parameters can be removed; maybe even more parameters are no longer needed.

2020-10-27 21:36 UTC, davideschiavone commented
Hi @Silabs-ArjanB , I made those changes

2020-10-28 06:54 UTC, Silabs-ArjanB commented on rtl/include/cv32e40p_apu_core_pkg.sv
>     /////////////////////////////////////////////////////////////////////////////
Can you remove this comment section as well and then please go ahead with the merge

2020-10-28 06:55 UTC, Silabs-ArjanB reviewed
Hi Davide, one last small thing< can you also please remove the outdated comment in the package file? After that, please go ahead with the merge

2020-10-28 07:09 UTC, davideschiavone commented
Done sorry, forgot that comment @Silabs-ArjanB

2020-10-28 07:10 UTC, merged