Core v mcu
openhwgroup/cv32e40p pull request #610
Opened 2021-01-25 14:41 UTC by davideschiavone

It removes the PMP for #609 and updates the src file to use the FF reg file.
It includes the PR to be accepted #604

This PR should be merged after #604 and after having a LEC CI in place

2021-01-25 15:10 UTC, MikeOpenHWGroup requested changes
The core-v-mcu should not be using its own manifest for the cv32e40p.  This should be read in directly from a manifest in the cv32e40p repo.

2021-01-25 15:18 UTC, Silabs-ArjanB approved these changes

2021-01-25 15:29 UTC, davideschiavone commented
> 
> 
> The core-v-mcu should not be using its own manifest for the cv32e40p. This should be read in directly from a manifest in the cv32e40p repo.

Can you please open an issue on the core-v-mcu repository then? we decided to maintain the src_file and Bender too for the PULP team. If we want to use the manifest in the current pulp-based openHW MCU we should open an issue against that in that repo. In the core side there is nothing wrong. Thanks for pointing it out!

2021-01-25 15:50 UTC, MikeOpenHWGroup commented
> Can you please open an issue on the core-v-mcu repository then?

Will do @davideschiavone.  Thanks.

2021-02-01 19:04 UTC, Silabs-ArjanB approved these changes

2021-02-01 20:48 UTC, MikeOpenHWGroup approved these changes

2021-02-02 09:18 UTC, merged