remove pmp unused file
openhwgroup/cv32e40p pull request #643
Opened 2021-05-08 15:11 UTC by davideschiavone

Signed-off-by: davideschiavone <davide@openhwgroup.com>

2021-05-11 06:59 UTC, Silabs-ArjanB requested changes
Can you also remove the following line from the User Manual, intro.rst:

The  ``rtl/cv32e40p_pmp.sv`` should not be included in the synthesis scripts as it is not supported.
This file is kept in the repository as a starting-point for users that want to implement their own.

2021-05-20 10:31 UTC, davideschiavone commented
done @Silabs-ArjanB

2021-05-20 10:38 UTC, Silabs-ArjanB approved these changes

2021-05-20 11:02 UTC, davideschiavone commented
how can we fix the ECA in this case? @MikeOpenHWGroup

2021-05-20 13:27 UTC, MikeOpenHWGroup commented
> how can we fix the ECA in this case? @MikeOpenHWGroup

It appears you have committed this change using an email address that is not covered by your ECA.  You'll need to rebase and recommit.  We faced this issue recently, so I documented the procedure in the [core-v-verif GitCheats](https://github.com/openhwgroup/core-v-verif/blob/master/GitCheats.md#rebasing-a-previous-commit).

2021-05-20 19:04 UTC, davideschiavone commented
> 
> 
> > how can we fix the ECA in this case? @MikeOpenHWGroup
> 
> It appears you have committed this change using an email address that is not covered by your ECA. You'll need to rebase and recommit. We faced this issue recently, so I documented the procedure in the [core-v-verif GitCheats](https://github.com/openhwgroup/core-v-verif/blob/master/GitCheats.md#rebasing-a-previous-commit).

thanks @MikeOpenHWGroup ! it worked out 💯

2021-05-20 19:05 UTC, merged