lec script for synopsys and cadence
openhwgroup/cv32e40p pull request #682
Opened 2022-03-03 15:45 UTC by davideschiavone

Add formality script
Updated conformal script
Modified top script to clone automatically the reference/golden model and translated to bash
improved README
tried both on bash and tcsh

2022-03-04 15:36 UTC, davideschiavone commented
@Silabs-ArjanB, @MikeOpenHWGroup - comments?

2022-03-07 07:11 UTC, Silabs-ArjanB requested changes

2022-03-07 07:11 UTC, Silabs-ArjanB commented on scripts/lec/clone_reference.sh
> +if [ ! -d "./golden_reference_desing" ]; then
desing -> design (here and in other places in this script)

2022-03-07 07:11 UTC, Silabs-ArjanB commented on scripts/lec/lec.sh
> +  export GOLDEN_RTL=$(pwd)/golden_reference_desing/cv32e40p/rtl
desing -> design

2022-03-07 16:23 UTC, davideschiavone commented
thanks @Silabs-ArjanB

2022-03-07 16:40 UTC, davideschiavone commented
@Silabs-ArjanB - can I use Squash and Merge?

2022-03-07 16:42 UTC, Silabs-ArjanB commented
> @Silabs-ArjanB - can I use Squash and Merge?

Sure

2022-03-07 17:54 UTC, MikeOpenHWGroup approved these changes

2022-03-07 21:49 UTC, merged