Documentation - typos
openhwgroup/cv32e40p pull request #712
Opened 2022-06-17 11:52 UTC by wzag

I believe it was a typo to initialize j twice

2022-06-20 13:41 UTC, davideschiavone commented
thanks @wzag for your PR - @pascalgouedo , the leader of the PULP extensions will review your proposal - meanwhile, may I ask you to do the PR again the dev branch instead of the master branch? thanks a lot
Davide

2022-06-24 10:24 UTC, pascalgouedo requested changes

2022-06-24 10:24 UTC, pascalgouedo commented on docs/source/corev_hw_loop.rst
> +The innermost loop, from startO to endO, adds to %[i] three times 1 and
The innermost loop, from startZ to endZ, adds to %[i] three times 1 and

2022-06-24 10:24 UTC, pascalgouedo commented on docs/source/corev_hw_loop.rst
>  it is executed 10x10 times. Whereas the outermost loop, from startO to endO,
it's loop body is executed 10x10 times. Whereas the outermost loop, from startO to endO,

2022-09-07 12:36 UTC, davideschiavone commented
what's the status of this @pascalgouedo ? If we do not merge we should close

2022-09-07 13:54 UTC, pascalgouedo commented
Hi @Davide
First correction is ok and second one is not.
Moreover this PR is on master and not on dev so I think we should drop it.
I have anyway taken it into account in my local updates I am going to push at some time.

2022-09-09 06:52 UTC, pascalgouedo commented
This feedback has been included in PR #720.

2022-09-09 06:52 UTC, closed without merging