Adding support for RVFI
openhwgroup/cv32e40p pull request #717
Opened 2022-08-03 16:02 UTC by YoannPruvost

First step toward full RVFI support on the cv32e40p.
For now, only the necessary signals for the ci test are correctly populated

2022-08-03 16:33 UTC, davideschiavone requested changes

2022-08-03 16:33 UTC, davideschiavone commented on bhv/cv32e40p_tb_wrapper.sv
> +  cv32e40p_rvfi rvfi_i (
hi @YoannPruvost , thanks for your contribution.

Can you pls add an ifdef to include or not this module ?

not all the EDA tools will support this module

2022-08-04 16:11 UTC, YoannPruvost commented on bhv/cv32e40p_tb_wrapper.sv
> +  cv32e40p_rvfi rvfi_i (
Hi @davideschiavone it's done

2022-08-10 14:15 UTC, davideschiavone approved these changes

2022-08-10 14:15 UTC, merged