Dev rvfi 2
openhwgroup/cv32e40p pull request #743
Opened 2022-11-30 16:03 UTC by YoannPruvost

Better implementation of RVFI for e40p.
Previous version was not compatible with xcelium.
This implementation focus on getting the ci_checks working.

Still a work in progress

2022-12-01 20:03 UTC, MikeOpenHWGroup commented on bhv/insn_trace.sv
> +  `define DEFINE_CSR(CSR_NAME) \
Please add a license header.  At a minimum:
```
// Copyright 2022 Dolphin Design
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
```

2022-12-01 20:04 UTC, MikeOpenHWGroup requested changes
Technical content LGTM.  Please add a comment header to `insn_trace.sv`.

2022-12-02 10:25 UTC, YoannPruvost commented on bhv/insn_trace.sv
> +  `define DEFINE_CSR(CSR_NAME) \
Done

2022-12-05 10:10 UTC, davideschiavone requested changes

2022-12-05 10:10 UTC, davideschiavone commented on bhv/cv32e40p_rvfi.sv
> +    input logic              nmi_pending_i,
we don't have NMI signals AFAIK, what do you mean here?

2022-12-05 10:10 UTC, davideschiavone commented on bhv/cv32e40p_rvfi.sv
> +    /*
can we remove these comments?

2022-12-05 10:20 UTC, YoannPruvost commented on bhv/cv32e40p_rvfi.sv
> +    input logic              nmi_pending_i,
I started the implementation by copy pasting the rvfi from the e40x. This still need a lot of cleaning to remove unnecessary bits.

2022-12-06 12:31 UTC, merged