Adding FPU & ZFINX support on rvfi
openhwgroup/cv32e40p pull request #799
Opened 2023-04-20 10:05 UTC by YoannPruvost

2023-04-20 14:08 UTC, davideschiavone requested changes

2023-04-20 14:08 UTC, davideschiavone commented on bhv/cv32e40p_rvfi_trace.sv
> +      rs1 = 6'b100000 | rvfi_frs1_addr;
using the OR makes it less readable, can we just extend it?

like

```
rs1 = {1'b1, rvfi_frs1_addr};
```

2023-04-20 14:08 UTC, davideschiavone commented on bhv/cv32e40p_rvfi_trace.sv
> +  localparam FPU = 1;
should we have this as a parameter?

2023-04-20 14:08 UTC, davideschiavone commented on bhv/pipe_freeze.sv
> +typedef struct {
if this module is used only in the tracer, can you please call it pipe_freeze_trace.sv?

2023-04-21 03:24 UTC, YoannPruvost commented on bhv/pipe_freeze.sv
> +typedef struct {
done

2023-04-21 03:25 UTC, YoannPruvost commented on bhv/cv32e40p_rvfi_trace.sv
> +      rs1 = 6'b100000 | rvfi_frs1_addr;
you are right
it's done ;)

2023-04-21 03:27 UTC, YoannPruvost commented on bhv/cv32e40p_rvfi_trace.sv
> +  localparam FPU = 1;
We need them to reuse the log file part of the former tracer.
Still I moved it from localparam to global param to match the core configuration

2023-04-24 06:59 UTC, merged