mstatus fs addition & bug corrections
openhwgroup/cv32e40p pull request #801
Opened 2023-04-21 15:08 UTC by pascalgouedo

Issue #170 correction: Adding MSTATUS.FS/SD

Issue #724 correction: Illegal exception for unknown F instructions.

Move from PULP_ZFINX to ratified v1.0 ZFINX.
Issue #725 correction: Illegal exception for FMV/FLW/FSW when ZFINX.
Updated MISA value and make MSTATUS.FS/SD ZFINX dependent.

Move PULP_ZFINX parameter to ZFINX in all RTL files.
Removed PULP_XPULP, PULP_CLUSTER, FPU, PULP_ZFINX assertions.

Issue #174 and #169 correction: Flush instructions following CSRW to FRM/FCSR.

Issue #741 correction: Illegal exception when CSRW to uhartid and privlv.

2023-04-24 07:00 UTC, davideschiavone requested changes

2023-04-24 08:19 UTC, pascalgouedo commented on bhv/cv32e40p_tb_wrapper.sv
> +      .ZFINX           (PULP_ZFINX),
I wanted RTL to be compliant with present core-v-verif TB.
I am going to align all bhv and core-v-verif files to ZFINX once Yoann has submitted a final core-v-verif PR with full FPU & Zfinx support.

2023-04-28 14:56 UTC, pascalgouedo commented on bhv/cv32e40p_tb_wrapper.sv
> +      .ZFINX           (PULP_ZFINX),
Done with commits below

2023-05-10 12:42 UTC, davideschiavone approved these changes

2023-05-10 12:45 UTC, merged