Update Instruction Set Extension Document
openhwgroup/cv32e40p pull request #811
Opened 2023-05-23 14:24 UTC by NandniJamnadas

Added documentation for 16-bit x 16-bit multiplication pseudo-instructions operations.

This is where `cv.mul* rD, rs1, rs2` is `cv.mul*n rD, rs1, rs2, 0`.

    * doc/source/instruction_set_extensions.rst

2023-05-25 14:36 UTC, NandniJamnadas commented on docs/source/instruction_set_extensions.rst
> +  :class: no-scrollbar-table
Thank you for the feedback. I have added a short paragraph on pseudo-instructions in the specification.

2023-05-25 15:08 UTC, jeremybennett requested changes
Suggested clarification of wording, but then I am happy.

2023-05-25 15:08 UTC, jeremybennett commented on docs/source/instruction_set_extensions.rst
> +This makes it easier to program as we gain clarity on the intention of the programmer.
Pseudo-instructions do not exist in the actual hardware. They are accepted by the assembler and mapped to appropriate actual instructions.  This is very common with standard RISC-V - for example ``nop`` is a pseudo-instruction which maps to `addi x0, x0, 0`.

2023-06-01 12:23 UTC, pascalgouedo commented
Hi @NandniJamnadas 
As discussed in mail thread, I included your updates in PR #815.
So I close this PR.
Cheers,
Pascal.

2023-06-01 12:23 UTC, closed without merging