3 RTL Issues corrections
openhwgroup/cv32e40p pull request #841
Opened 2023-07-31 13:07 UTC by pascalgouedo

Issue #838 correction
Issue #730 correction
Issue #840 correction

2023-07-31 13:28 UTC, davideschiavone requested changes

2023-07-31 13:28 UTC, davideschiavone commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
why are you explicitly checking the NUM_MPHCOUNTERS? this parameter was already part of v1.0.0

2023-07-31 13:57 UTC, davideschiavone commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
to me looks strange, are we verifying the v2 for each possible number of counters?
If not, what are the differences (and why) between v1 and v2 when we have more than 1 counter?

2023-07-31 14:37 UTC, pascalgouedo commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
not all possible counters number but maybe going up to 2 or 4 for v2 ...

2023-07-31 14:38 UTC, davideschiavone commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
are v1 and v2 LEC when the number of counters are 4? and if not, why?

2023-07-31 14:54 UTC, pascalgouedo commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
v1 is using default value 1 for NUM_MHPMCOUNTERS.
if we force 4 in v1 golden ref and in v2 they are LEC.
but as v1 verification didn't verify anything else than value 1, how to be sure the 3 new counters are working properly?
=> going to be verified in v2 config only (maybe, just thinking about that).
we are not re-opening v1 verif so value 1 is mandatory.
you are thinking about if no bug found in v2 and value = 4, then we can authorize v1 with value = 4 (as long as LEC)?

2023-07-31 15:04 UTC, pascalgouedo commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
all 29 mhpmcounter CSR accesses are checked in mhpmcounter29_csr_access_test_* tests.
but all event sources are only checked on mhpmcounter3 in perf_counters_instructions test.

2023-07-31 15:06 UTC, davideschiavone commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
but if v1 and v2 are LEC in the number of counters (up to 4 at least), does it matter that none verified that v1 worked with 4 counters if it is equivalent to v2 - that is my 2 cents 

If you verified v2 with 7 counters, and I do a project with 8 counters and tag it as v3, shall I change the mimpid even if they are LEC? I would not do it...

@Silabs-ArjanB , what do you think?

2023-07-31 15:12 UTC, pascalgouedo commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
> If you verified v2 with 7 counters, and I do a project with 8 counters and tag it as v3, shall I change the mimpid even if they are LEC? I would not do it...

This is a point I though about as well when updating the User Manual.
If we want any one to be free to use any value for NUM_MHPMCOUNTERS then we must verify that all 29 counters are working properly.

@MikeOpenHWGroup Any thought on that point?

2023-07-31 15:14 UTC, pascalgouedo commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
> but if v1 and v2 are LEC in the number of counters (up to 4 at least), does it matter that none verified that v1 worked with 4 counters if it is equivalent to v2 - that is my 2 cents

So you rely on v2 verification to ensure v1 + NUM_MHPMCOUNTERS > 1 is OK

2023-08-01 14:43 UTC, Silabs-ArjanB commented on rtl/cv32e40p_cs_registers.sv
> +          csr_rdata_int = (FPU || COREV_PULP || COREV_CLUSTER || (NUM_MHPMCOUNTERS > 1)) ? 32'h1 : 'b0;
> but if v1 and v2 are LEC in the number of counters (up to 4 at least), does it matter that none verified that v1 worked with 4 counters if it is equivalent to v2 - that is my 2 cents
> 
> If you verified v2 with 7 counters, and I do a project with 8 counters and tag it as v3, shall I change the mimpid even if they are LEC? I would not do it...
> 
> @Silabs-ArjanB , what do you think?

I would also not change mimpid if there is no actual RTL change (but just more extensive verification)

2023-08-01 16:47 UTC, MikeOpenHWGroup commented
> This is a point I though about as well when updating the User Manual.
If we want any one to be free to use any value for NUM_MHPMCOUNTERS then we must verify that all 29 counters are working properly.

Yes, that is my opinion also.  It is fine to say "only NUM_MHPMCOUNTERS == 1 has been verified" in the User Manual.  By if we allow the parameter to be set to any value, then we need to verify that is works.  This particular feature is high-effort, low-reward, so I recommend we stick to num-counters==1.  If a user of our IP wants to use a different number of counters, they can verify that for themselves.

2023-08-01 17:09 UTC, pascalgouedo commented
So
- v1 : mimpid = 0 implies NUM_MHPMCOUNTERS == 1
- v2 : mimpid = 1 implies NUM_MHPMCOUNTERS == 1
- NUM_MHPMCOUNTERS > 1 : mimpid = 2?
or totally remove NUM_MHPMCOUNTERS check for mimpid?

2023-08-01 17:32 UTC, MikeOpenHWGroup commented
Hmm.  We should not remove the NUM_MHPMCOUNTERS check for mimpid since increasing the number of counters is clearly a software-impacting change.  I would suggest `NUM_MHPMCOUNTERS > 1 : mimpid >= 2`.  Keep in mind that to have a globally unique identifier for the core you need at least `mimpid`, `marchid` and `mvendorid`.

2023-08-02 05:57 UTC, Silabs-ArjanB commented
> or totally remove NUM_MHPMCOUNTERS check for mimpid?

As long as no actual RTL changes are made related to NUM_MHPMCOUNTERS (more specifically if the RTL is LEC clean for the original parameter set and SEC clean for any other NUM_MHPMCOUNTERS value that you want to claim to support) , then _mimpid shall not be changed either_ because of a change in verified NUM_MHPMCOUNTERS value(s).

2023-08-02 06:38 UTC, davideschiavone commented
> > or totally remove NUM_MHPMCOUNTERS check for mimpid?
> 
> As long as no actual RTL changes are made related to NUM_MHPMCOUNTERS (more specifically if the RTL is LEC clean for the original parameter set and SEC clean for any other NUM_MHPMCOUNTERS value that you want to claim to support) , then _mimpid shall not be changed either_ because of a change in verified NUM_MHPMCOUNTERS value(s).

completely agree - LEC is the strongest point of differentiating between the 2 versions - 

so if v2 and v1 are LEC on the number of counters, then why one would change the mimpid? 


The mimpid is used by the software - would the software change between v1 with 4 counters and v2 with 4 counters (with all the other parameters set to their v1 version?) if the answer is no, which I understood it is as the 2 are LEC, then there is no need for changing the mimpid. 

So for this specific PR, I would simply remove the counters from the OR equation on the mimpid CSR assignment.

2023-08-02 08:11 UTC, pascalgouedo commented
LEC between v1 and v2 with NUM_MHPMCOUNTERS = 4 doesn't mean the 3 counters not verified neither for v1 and v2 are working fine.
For me mimpid = 0 or 1 means "verified v1 & v2 version with its defined set of parameters".
Any other value means "not verified set of parameters" as of today.
This is not used to understand how many counters you have, you can figure out that with some smart C function using CSR accesses and illegal exceptions.

2023-08-02 09:53 UTC, davideschiavone commented
for me v1 and v2 means they are not LEC and thus the SW needs to differentiate. It is not an ID of the verification but it serves SW. 

If by any chance the verification v2 would end up be identical to v1 even on the FPU or PULP, then we would not change the mimip, even if they were unverified.

2023-08-02 11:55 UTC, Silabs-ArjanB commented
@pascalgouedo The sentence you quote is there indeed, but I consider it inaccurate. Also it conflicts with the remaining content of that chapter (as well as our intent)

2023-08-03 05:56 UTC, davideschiavone commented
Agree with @Silabs-ArjanB , the sentence is not accurate - so what I vote for is to remove the NUM_COUNTERS from the `mimpid` csr assignment. We can add in the documentation up to which number they have been verified and whether they are LEC up to that number

2023-08-03 13:42 UTC, merged