Refactor of LEC/SEC scripts
openhwgroup/cv32e40p pull request #929
Opened 2024-01-02 11:43 UTC by MarioOpenHWGroup

- LEC script refactor
- SEC process always supported using Siemens SLEC App

2024-01-03 15:07 UTC, pascalgouedo requested changes
Did you add those slec scripts to do the same than lec, meaning v1 versus v2 with v1 parameters setting?
Because as of today as the top level is cv32e40p_core and not cv32e40p_top and so it is excluding FPU.
We could extend the methodology for the future to be able to check v2 with v2+++ by moving top_module to cv32e40p_top.
I have done that for lint so I can lint v1 and all configurations of v2...
In fact to deal with configurability, I added a new top module (cv32e40p_wrapper which instantiates cv32e40p_top) which imports a config package which is selected by shell script.

2024-01-03 15:13 UTC, pascalgouedo requested changes

2024-01-03 15:13 UTC, pascalgouedo commented on scripts/slec/siemens/Makefile
> +#             Copyright 2006-ntor Graphics Corporation
Mentor Graphics

2024-01-12 13:01 UTC, MarioOpenHWGroup commented
I have also added the Cadence SEC script using JasperGold, if you can review the PR again :)

2024-02-21 16:50 UTC, pascalgouedo approved these changes

2024-02-28 11:23 UTC, merged