RISC-V ISA Formal Verification files for SiemensEDA OneSpin tool.
openhwgroup/cv32e40p pull request #993
Opened 2024-05-30 15:10 UTC by pascalgouedo

2024-05-30 17:29 UTC, MikeOpenHWGroup requested changes
Thanks @pascalgouedo.  One request and one question:
**Request**: can you add Solderpad license headers to these files (the one-liner SPDX header is sufficient)?
**Question**: is the obfuscated TcL file readable by tools other than OneSpin?

2024-05-31 07:08 UTC, pascalgouedo commented
Hi Mike,

I am pretty sure this encrypted tcl file is using a OneSpin private key like it is done for automatically generated assertions SystemVerilog file.
And anyway I think nothing here can be used in any other tool.

For Solderpad license I should maybe ask (again) to SiemensEDA to be sure.

Only restrictions I remember was about FormalVerifPlan excel file, not on those tool setup files.

2024-05-31 12:39 UTC, MikeOpenHWGroup commented
> For Solderpad license I should maybe ask (again) to SiemensEDA to be sure.

Thanks.  This is important to OpenHW for obvious reasons.

2024-06-03 15:06 UTC, MikeOpenHWGroup approved these changes

2024-06-03 15:06 UTC, merged